### PR TITLE
Basic example configs

### PR DESCRIPTION
**Pull request by SirFancyBacon**
Added extremely basic example .conf files; one for each type.

Mostly just testing out Github with this; i'll overwrite most of this later i am sure. :)

### CODE REVIEW

**Comment by SirFancyBacon** [comment]
Updated with a lot more changes.

Let me know what you think

**Comment by NeumimTo** [comment]
I think it would be better if you could commit and push the folder structure as well.

**Comment by SirFancyBacon** [comment]
More than just class, race, and skilltree?
added those in my repo so i figured they'd show up here as well:
https://github.com/hellbringer616/NT-RPG-Configs-And-Assets

**Comment by NeumimTo** [comment]
Awesome, thanks. Just these 3 folders will be fine, no need for anything else.

**Comment by SirFancyBacon** [comment]
Uploaded the 3 folders and restructured a lot of the files i pushed with it.

Gives more freedom for development of the classes/races.

What do you think?

**Comment by NeumimTo** [comment]
In case you have a property which name ends with _mult
You do not have to specify its  value to be 1. such as 

    fire_damage_protection_mult: 1.0

1.0 is already default value for any *_mult property.

**Comment by SirFancyBacon** [comment]
Okay i'll make those adjustments tonight.
I added them because "WEAPON_MERGE_STRATEGY":1

I was concerned if i didn't add it then it would take the 0.1 from race and only apply that to the class, so i'd end up with 0.1 instead of 1.1

**Pull request merged**
