### PR TITLE
API update to Snapshot 13

### PR DESCRIPTION
**Pull request by SirFancyBacon**
An attempt to fix the resource pack issue; untested.

Changes:
Changed the texture format from 1 to 3 (MC v1.12.x)
Renamed to items to verify a theory of how NT-RPG works with item names (may break things)

### CODE REVIEW

**Comment by NeumimTo** [comment]
I think you commited wrong file, this one has still version 1.

**Comment by SirFancyBacon** [comment]
Whoops; copied the wrong file to the zip once i was done editing; all fixed now!

**Comment by SirFancyBacon** [comment]
Renamed this since i'm too lazy to fork just to keep this open :p so all the above comments are useless!!
Anyway, this should fix the assets and bring it up to Snapshot 13 compatibility.

Untested since i run a modded server; but it should be working fine.

**Comment by NeumimTo** [comment]
Thanks man!

**Pull request merged**
